name: SchlickArt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90662
title: SchlickArt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#2f2f2f'
    - '#5c5c5c'
    - '#a8a8a8'
  brandStrength: 0.8578054988756776
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
